name = "ごんぎつね"
author = "Vivliostyle.org"
files = [
  "img/Vulpes_vulpes_japonica_in_Mount_Shirouma_1996-09-29.jpg",
  "img/gon.jpg",
  "index.html",
  "responsive.html",
  "scss/base/_contents.scss",
  "scss/base/_format.scss",
  "scss/base/_typography.scss",
  "scss/style.scss",
  "style.css"
]
previewImeges = [
  "screenshots/p1.png"
]
tags = [
  "vertical_text",
  "ruby",
  "page_margin_box",
  "page_counter",
  "ja"
]
