name = "白馬岳"
author = "Vivliostyle.org"
files = [
  "img/Mount_Shirouma_from_Mount_Korenge_2000-7-31.jpg",
  "img/Shiroumadake_from_Shiroumayari_1999-10-10.jpg",
  "img/bg-left.png",
  "img/bg-right.png",
  "img/photo_shirouma.jpg",
  "index.html",
  "responsive.css",
  "responsive.html",
  "scss/base/_contents.scss",
  "scss/base/_format.scss",
  "scss/base/_typography.scss",
  "scss/style.scss",
  "style.css"
]
previewImeges = [
  "screenshots/p1.png"
]
tags = [
  "Vertical_text",
  "multi_column",
  "ruby",
  "page_margin_box",
  "ja"
]
